package com.newspace.festinha;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Evento implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Evento() {
    }




}