package com.newspace.festinha;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Pessoa implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Data de Nascimento")
	private java.util.Date nasc;

	@org.kie.api.definition.type.Label(value = "Nome")
	private java.lang.String nome;

	public Pessoa() {
	}

	public java.util.Date getNasc() {
		return this.nasc;
	}

	public void setNasc(java.util.Date nasc) {
		this.nasc = nasc;
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public Pessoa(java.util.Date nasc, java.lang.String nome) {
		this.nasc = nasc;
		this.nome = nome;
	}

}