package com.newspace.festinha;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Pessoa implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Pessoa() {
    }




}